# Generated by Django 4.1.7 on 2023-05-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_produitcommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='commande_produit',
            field=models.ManyToManyField(blank=True, to='magasin.commande'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
