# Generated by Django 4.1.7 on 2023-05-09 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_produit_commande_produit_produit_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_produits', to='magasin.produit')),
            ],
        ),
        migrations.DeleteModel(
            name='ProduitCommande',
        ),
    ]
